Feature/#13
Like-House/FE pull request #25
Opened 2024-07-15 00:30 UTC by kimjj0

## 🎈 어떤 이슈와 관련된 PR인가요?
> 이슈 번호를 기입해주세요!

## 📝 해당 PR에서 작업한 내용을 설명해주세요.
> 이번 PR은 어떤 작업을 담고 있는지 간략히 설명해주세요!
- [x] 아바타 제작

### 작업 내용과 관련된 스크린샷을 첨부해주세요. (선택 사항)
> 피그마 스크린샷
<img width="170" alt="스크린샷 2024-07-15 오전 9 16 29" src="https://github.com/user-attachments/assets/0c6830ae-3465-4977-896b-275a6f6f7a5a">

> 작업 결과 스크린샷
<img width="170" alt="스크린샷 2024-07-15 오전 9 18 37" src="https://github.com/user-attachments/assets/6e84f5ab-535a-4815-b673-2289def339a3">

## 💬 리뷰어 전달 사항
> Avatar 컴포넌트를 사용할 페이지에서 const size = "100px" 같이 size 변수를 사용하는 게 맞을까요?

> 그리고 아래 사진과 같이 자꾸 prettier 때문에 경고문이 뜨는데 해결 방법 아시는 분 알려주시면 감사하겠습니다..

<img width="1304" alt="스크린샷 2024-07-15 오전 9 20 27" src="https://github.com/user-attachments/assets/b3e16503-d591-4ac9-9abb-20de292575ad">

2024-07-15 10:44 UTC, hijjoy approved these changes
eslint와 prettier가 충돌이나서 그 prettier경고문이 나오는건데 
prettier를 끄고 개발 진행하시면 lint적용이 됩니다 ! 
prettier를 끄고 원래 개발 진행하셨던 파일 다시 저장하면 사라질 것 같습니다

2024-07-15 10:44 UTC, hijjoy commented on src/components/common/avatar/Avatar.jsx
> +const Avatar = ({ src, size }) => {
어짜피 width, height가 동일하고 여러 크기가 있을 수 있다고 생각해서 저는 size 변수로 받는게 좋은 것 같다고 생각합니다 !

2024-07-15 12:20 UTC, kimjj0 commented on src/components/common/avatar/Avatar.jsx
> +const Avatar = ({ src, size }) => {
넵 감사합니다 !!

2024-07-16 02:41 UTC, dydals3440 requested changes, later dismissed

2024-07-16 02:41 UTC, dydals3440 commented on src/components/common/avatar/Avatar.style.js
> +	width: ${({ size }) => size};
지금 이런식으로, size만 픽셀 형태로 받아서, 컴포넌트를 제작했는데, 이런식으로 넘기기 보다.
size가 sm, md, lg 일떄 각각 픽셀 형태를 고정시켜보는 것도 좋을 것 같아요!!

그러고, 지금은 무조건 원인 형태로, 나오게 되는데, 요구사항에 따라, 직사각형 모양의 프로필도 생길 수 있으니 이를 대응해보는 것은 어떨까요? shape 프롭을 받아서, circle일떄는 원, rect일떄 사각형 이런식으로요!!!

아래 문서 참고하시면 좋을 것 같습니다~!

https://youngju-js.tistory.com/66

2024-07-16 05:55 UTC, kimjj0 commented on src/components/common/avatar/Avatar.style.js
> +	width: ${({ size }) => size};
수정해봤습니다 감사합니다 !

2024-07-16 06:14 UTC, joyfulond approved these changes
수고하셨습니다

2024-07-16 06:14 UTC, joyfulond commented on src/components/common/avatar/Avatar.style.js
> +const sizeStyles = {
잘 나누신 것 같아요!!

2024-07-16 06:14 UTC, joyfulond commented on src/components/common/avatar/Avatar.style.js
> +const shapeStyles = shape => {
👍🏻

2024-07-16 06:14 UTC, joyfulond commented on src/components/common/avatar/Avatar.style.js
> +	object-fit: cover;
얘도 첨 봐요! 공부하겠습니다

콘텐츠의 비율을 유지하면서, 컨테이너의 크기에 맞춰 콘텐츠를 조정. 이 과정에서 콘텐츠의 일부가 잘릴 수 있음. 이 속성은 주로 이미지나 비디오가 컨테이너의 모든 영역을 채우게 할 때 사용됨. 👀

2024-07-16 10:56 UTC, kimjj0 commented on src/components/common/avatar/Avatar.style.js
> +const sizeStyles = {
감사합니다 !!

2024-07-16 10:57 UTC, kimjj0 commented on src/components/common/avatar/Avatar.style.js
> +	object-fit: cover;
저도 구글링 하면서 해서 .. 화이팅입니다 😊

2024-07-16 11:59 UTC, hyeyoon23 reviewed
수고하셨습니다 !🍀

2024-07-16 11:59 UTC, hyeyoon23 commented on src/components/common/avatar/Avatar.style.js
> +	object-fit: cover;
저도 첨보는 거 같아요! 배워갑니당🤩✨

2024-07-16 18:21 UTC, daindaind approved these changes

2024-07-16 18:21 UTC, daindaind commented on src/components/common/avatar/Avatar.jsx
> +const Avatar = ({ src, size, shape }) => {
shape, size에 대한 default값을 주는 것이 좋아보입니다. shape을 주지 않으면 아무 스타일도 지정이 안되네요. 의도하신 것이라면 수정하지 않아도 됩니다! 그러나 보통 Avatar 컴포넌트를 쓸 때 동그란 UI를 예상하고 사용하기 때문에 주로 사용되는 스타일이라면 아예 default를 지정해버려도 괜찮을 것 같다는 생각이 듭니다.

2024-07-16 18:21 UTC, daindaind commented on src/components/common/avatar/Avatar.style.js
> +			border-radius: 0;
shape이 rect일 때 border-radius가 완전 0인 것보다는 살짝 끝이 둥근 편이 미관상 더 좋을 것 같습니다. (개인적인 의견입니다..)

2024-07-16 18:21 UTC, daindaind commented on src/components/common/avatar/Avatar.jsx
> +	return <S.Image src={src} size={size} shape={shape} />;
해당 컴포넌트를 사용할 때 src를 지정해주지 않으면 오류가 뜨는데, 부모 컴포넌트로부터 src를 받지 않으면 default 이미지라도 보여줘야할 것 같습니다. 또는, src가 존재하지 않을 때 아예 img 자체를 반환하지 않는 방향으로 해서 오류를 막는 것이 좋아보입니다. 

일단 유저 프로필이 없는 (src가 없는) 상황일 때 보여줄 default user profile 이미지가 필요하실 것 같아서 디자이너분께 요청드리겠습니다. 이미지 받으면 바로 전달드릴게요!

2024-07-16 18:24 UTC, daindaind approved these changes

2024-07-16 18:24 UTC, daindaind commented on src/components/common/avatar/Avatar.jsx
> +const Avatar = ({ src, size, shape }) => {
지금 당장 필요한 기능은 아닌데, 보통 다른 SNS 서비스를 보면 아바타를 클릭했을 때 해당 유저의 프로필 페이지로 이동이 됩니다. 지금 우리 서비스는 유저 프로필을 따로 볼 수는 없지만, 만일 해당 기능이 추가된다면 만들어주신 아바타 컴포넌트에 onClick 속성에 전달할 prop도 필요해보입니다. 물론 해당 컴포넌트를 호출하는 부모 컴포넌트 단에서 button으로 감싸면 비슷한 효과를 낼 수는 있지만, 이렇게 사용하면 조금 번거로울 수 있을 것 같습니다.

2024-07-17 00:47 UTC, kimjj0 commented on src/components/common/avatar/Avatar.jsx
> +const Avatar = ({ src, size, shape }) => {
두 값 모두 default 값 지정했습니다.

2024-07-17 00:47 UTC, kimjj0 commented on src/components/common/avatar/Avatar.style.js
> +			border-radius: 0;
저도 그렇게 생각해서 살짝 둥글게 했습니다..!

2024-07-17 00:49 UTC, kimjj0 commented on src/components/common/avatar/Avatar.jsx
> +	return <S.Image src={src} size={size} shape={shape} />;
src가 없을 때 null값을 반환하도록 수정했는데, 이것보다는 default img를 반환하는게 나을 것 같아 디자이너 분께 전달 받은 이미지로 추후에 수정하겠습니다.

2024-07-17 00:51 UTC, kimjj0 commented on src/components/common/avatar/Avatar.jsx
> +const Avatar = ({ src, size, shape }) => {
onclick props를 추가했습니다. onclick prop를 넘기면 onclick 이벤트가 생기며 커서를 pointer로 바꾸는 스타일을 지정했고, onclick prop을 넘기지 않으면, 이벤트가 생기지 않고 커서도 default 값을 유지하도록 수정했습니다.

2024-07-17 04:46 UTC, daindaind commented on src/components/common/avatar/Avatar.jsx
> +const Avatar = ({ src, size, shape }) => {
확인했습니다!

2024-07-17 04:46 UTC, daindaind commented on src/components/common/avatar/Avatar.style.js
> +			border-radius: 0;
확인했습니다!

2024-07-17 04:48 UTC, daindaind commented on src/components/common/avatar/Avatar.jsx
> +	return <S.Image src={src} size={size} shape={shape} />;
확인했습니당! 디자이너님께 요청드렸습니다!

2024-07-17 04:49 UTC, daindaind commented on src/components/common/avatar/Avatar.jsx
> +const Avatar = ({ src, size, shape }) => {
확인했습니다~!

2024-07-17 05:22 UTC, merged