[FEAT]feature/#33 PhotoMainPage 구현
Like-House/FE pull request #37
Opened 2024-07-18 12:47 UTC by kimjj0

## 🎈 어떤 이슈와 관련된 PR인가요?
> 이슈 번호를 기입해주세요!

## 📝 해당 PR에서 작업한 내용을 설명해주세요.
> 이번 PR은 어떤 작업을 담고 있는지 간략히 설명해주세요!
- [x] 캘린더 영역 잡기
- [x] 목데이터 이용해 드롭다운에 메뉴 설정

### 작업 내용과 관련된 스크린샷을 첨부해주세요. (선택 사항)
> 피그마 스크린샷
<img width="1129" alt="스크린샷 2024-07-18 오후 9 46 24" src="https://github.com/user-attachments/assets/905fa390-816e-424d-805a-7c48a458677a">

> 작업 결과 스크린샷
<img width="1728" alt="스크린샷 2024-07-18 오후 9 47 14" src="https://github.com/user-attachments/assets/bc866003-ab0b-46f8-90a0-3e5995f66e8a">

## 💬 리뷰어 전달 사항
> 아직 반응형 구현하지 않았는데 캘린더나 드롭다운 화면이 줄어들면 어떤 식으로 바꿔야할 지 의견 주시면 감사하겠습니다 🥲

2024-07-21 04:45 UTC, dydals3440 requested changes
반응형 확인한 이미지 리뷰에 첨부해서 올려주세요!

2024-07-22 08:46 UTC, kimjj0 commented
화면 줄어들었을 때 입니다. 모바일 크기에서는 사이드바의 위치가 위로 올라가야 앨범이 잘 보일 것 같습니다..!

<img width="1206" alt="스크린샷 2024-07-22 오후 5 27 43" src="https://github.com/user-attachments/assets/767e502d-6b0f-4a3e-99fa-d3b4a9266f52">

2024-07-22 09:31 UTC, hijjoy approved these changes
<img width="919" alt="스크린샷 2024-07-22 18 24 07" src="https://github.com/user-attachments/assets/c2d34c10-9f12-4afa-9d58-1f29f77dc73d">
혹시 그.. 가족 선택했을때는 이렇게 아래 빈칸이 많아지는데 수정이 가능할까요 ..? 

그리고 드롭다운 DropdownButtonArea에도 **cursor: pointer;**  넣으면 좋을 것 같습니다 ! 




사이드바 때문에 모바일 반응형이 조금 어려운 것. ㅏㅌ은데 제가 사이드바 대충 아래와 같이 수정해 올리도록 하겠습니다 ! 모달창하면서 같이 수정해주세요 !! 
![스크린샷 2024-07-22 18 29 32](https://github.com/user-attachments/assets/1edd482b-5fcb-46db-b7a5-74494afce9be)
![스크린샷 2024-07-22 18 13 26](https://github.com/user-attachments/assets/482e8360-20cc-4e95-922f-be42db3590a4)

2024-07-22 09:31 UTC, hijjoy commented on src/pages/photo/PhotoMainPage.style.js
> +	border-right: 8px solid #f6f6f6;
조금 사소한거지만 box-shadow: 0px 4px 10px 0px rgba(0, 0, 0, 0.05); 로 고치면 더 피그마랑 비슷할 것 같아요 !

2024-07-22 09:31 UTC, hijjoy commented on src/pages/photo/PhotoMainPage.style.js
> +const Picture = styled.img`
cursor: pointer; 츄가해주세요 !

2024-07-22 09:47 UTC, hijjoy approved these changes

2024-07-22 09:47 UTC, hijjoy commented on src/pages/photo/PhotoMainPage.jsx
그 콘솔에 계속 warning뜨는거 드롭다운에 $ 추가해주면 사라집니다 ! 
```
<S.DropdownLabel $isSelected={selectedMenu !== null}>
<S.DropdownMenuArea $isOpen={isOpen}>
```

2024-07-22 09:58 UTC, hijjoy commented on src/pages/photo/PhotoMainPage.jsx
d아 근데 $isOpen={isOpen}을 하면 안열리네용 이건 취소 ...

2024-07-22 10:57 UTC, kimjj0 commented on src/pages/photo/PhotoMainPage.style.js
> +	border-right: 8px solid #f6f6f6;
수정했습니다 !

2024-07-22 10:57 UTC, kimjj0 commented on src/pages/photo/PhotoMainPage.style.js
> +const Picture = styled.img`
수정했습니다 !

2024-07-22 10:58 UTC, kimjj0 commented on src/pages/photo/PhotoMainPage.jsx
에러가 안 없어지네요 😢

2024-07-22 10:59 UTC, kimjj0 commented on src/pages/photo/PhotoMainPage.style.js
> +	border-right: 8px solid #f6f6f6;
grid는 제가 수정하고 커밋을 안 한 것 같습니다. 다시 확인 부탁드려요 !! 그런데 문제가 사진 비율이 고정을 한다고 했는데 고정이 안되고 자꾸 달라집니다 ㅠㅠ

2024-07-22 10:59 UTC, kimjj0 commented on src/pages/photo/PhotoMainPage.style.js
> +	border-right: 8px solid #f6f6f6;
테블릿 화면은 수정 후 다시 커밋하겠습니다 !

2024-07-22 11:12 UTC, hijjoy commented on src/pages/photo/PhotoMainPage.style.js
> +	border-right: 8px solid #f6f6f6;
반응형은 디자이너님이 만드신후 시작하셔도될것같습니다 !!!

2024-07-22 13:19 UTC, kimjj0 commented on src/pages/photo/PhotoMainPage.style.js
> +	border-right: 8px solid #f6f6f6;
우선 버튼으로 다루는 걸로 수정해봤습니다 !!

2024-07-22 19:49 UTC, daindaind approved these changes

2024-07-22 19:49 UTC, daindaind commented on src/pages/photo/PhotoMainPage.jsx
콘솔에 뜨는 해당 경고창은 모든 prop에 $ 접두사를 붙여서 해결 가능합니다!

```javascript 
<S.DropdownContainer $size={size}>    {/* $ 접두사 추가 */}
	<S.DropdownButtonArea onClick={handleDropdown}>
		<S.DropdownLabel $isSelected={selectedMenu !== null}>
			{selectedMenu || label}
		</S.DropdownLabel>
		{isOpen ? closeIcon : openIcon}
	</S.DropdownButtonArea>
	<S.DropdownMenuArea $isOpen={isOpen}>
		{options.map((menu, index) => (
			<S.DropdownMenu key={index} onClick={() => selectMenu(menu)}>
				{menu}
			</S.DropdownMenu>
		))}
	</S.DropdownMenuArea>
</S.DropdownContainer>
```

이런 식으로 prop을 전달하면 원래 기본적으로 DOM 요소에서 제공되지 않는 prop을 쓸 때, 리액트에서 필터링하여 스타일에만 해당 prop을 사용할 수 있게 됩니다.

그러면 스타일 파일에서는 이렇게 해당 prop을 받을 수 있습니다.
```javascript
const DropdownMenuArea = styled.div`
	width: 100%;
	margin-top: 10px;
	padding: 12px 18px;
	border-radius: 10px;
	background-color: ${theme.COLOR.COMMON.WHITE};
	max-height: ${({ $isOpen }) => ($isOpen ? '500px' : '0')};   // $ 접두사 추가
	overflow: hidden;
	transition:
		max-height 0.5s ease-out,
		opacity 0.5s ease-out;
	opacity: ${({ $isOpen }) => ($isOpen ? '1' : '0')};
`;
```

다른 내용은 아래 링크를 참고해주세요!
https://oliviakim.tistory.com/169

2024-07-23 02:41 UTC, dydals3440 approved these changes

2024-07-23 02:41 UTC, dydals3440 commented on src/pages/photo/PhotoMainPage.jsx
> +		console.log(op);
console.log는 테스트 이후에 PR시 제거 부탁드립니다!

2024-07-23 02:41 UTC, dydals3440 commented on src/pages/photo/PhotoMainPage.jsx
> +	const filteredPicture = selectedOp
filter 함수만 사용해서, 굳이 Ternary Operation 사용하지 않고, 나타낼 수 있지 않을까 싶네요!!

2024-07-23 04:42 UTC, kimjj0 commented on src/pages/photo/PhotoMainPage.jsx
> +	const filteredPicture = selectedOp
그러면 드롭다운에서 옵션을 선택하지 않았을 때 사진이 안 나타나지 않나요??

2024-07-23 05:37 UTC, kimjj0 commented on src/pages/photo/PhotoMainPage.jsx
> +	const filteredPicture = selectedOp
수정했습니다 !!

2024-07-23 05:37 UTC, kimjj0 commented on src/pages/photo/PhotoMainPage.jsx
> +		console.log(op);
제거했습니다 !

2024-07-23 06:36 UTC, merged