[Feat] {feature/#39} 가족 관리 페이지 구현
Like-House/FE pull request #40
Opened 2024-07-19 10:55 UTC by joyfulond

## 🎈 어떤 이슈와 관련된 PR인가요?
> feature/#39

## 📝 해당 PR에서 작업한 내용을 설명해주세요.
> 이번 PR은 어떤 작업을 담고 있는지 간략히 설명해주세요!
- [x] 가족 공간 관리 페이지 구현
- [x] 가족 관리 페이지 구현

### 작업 내용과 관련된 스크린샷을 첨부해주세요. (선택 사항)
> 피그마 스크린샷
<img width="609" alt="스크린샷 2024-07-19 오후 7 52 29" src="https://github.com/user-attachments/assets/1ff3a74e-eadc-468c-9084-a7f5b5c4ae47">

> 작업 결과 스크린샷
<img width="1440" alt="스크린샷 2024-07-19 오후 7 53 27" src="https://github.com/user-attachments/assets/ca888f89-a1a3-464c-9f66-ab41ebd66585">
<img width="1440" alt="스크린샷 2024-07-19 오후 7 54 10" src="https://github.com/user-attachments/assets/f55a8630-c462-4c62-90fd-5036edcc1b9a">
<img width="1440" alt="스크린샷 2024-07-19 오후 7 54 23" src="https://github.com/user-attachments/assets/90fabea9-69db-4b0f-a824-8a8297be4173">

## 💬 리뷰어 전달 사항
> 상태 변경은 어떤 기능을 가지고 있는 버튼인가요? 잘 모르겠어서 빼고 구현하였습니다.

> 설정으로 들어가는 버튼은 언제쯤 만들어질까요? 🥲

> 해제나 차단 모달에 확인 버튼을 누르면 Alert 모달창이 한 번 더 뜨도록 구현하였습니다. 변동사항이 생기면 알려주세요!

2024-07-21 04:46 UTC, dydals3440 requested changes
반응형 확인한 이미지 리뷰에 첨부해서 올려주세요!

2024-07-22 20:08 UTC, daindaind approved these changes

2024-07-22 20:08 UTC, daindaind commented on src/pages/setting/FamilySpaceSettings/FamilySpaceSettings.jsx
> +        </Tooltip>
UI를 헷갈리게 드렸나 봅니다.. `<S.Icon src={link} alt='link Icon' />` 버튼은 클립보드 복사 버튼입니다. 사용자가 코드를 쉽게 복사할 수 있도록 버튼을 만든 것이고, 그 위에 까만 것은 툴팁이 아니고 코드를 재발급할 수 있는 또 다른 버튼입니다..

2024-07-22 20:08 UTC, daindaind commented on src/pages/setting/FamilySpaceSettings/FamilySpaceSettings.jsx
> +        </Tooltip>
코드 재발급 같은 경우, 코드 자체는 백엔드에서 줄 예정입니다!

2024-07-22 20:08 UTC, daindaind commented on src/pages/setting/FamilySettings/FamilySettings.jsx
> +                )}
이것도 약간 소통의 오류가 있었던 듯 합니다.. 
**주최자**일 때 버튼이 3개가 있습니다. `[가족 해제]`, `[정보 수정]`, `[차단]`
**일반 가족**일 때 버튼이 1개가 있습니다. `[정보 수정]`

정보 수정은 피그마에서처럼 가족 정보를 수정할 수 있는 페이지로 이동하는 버튼입니다.
이전 버전에는 `[상태 변경]`이라는 워딩을 사용했으나, 이게 많이 헷갈려하시는 것 같아서 `[정보 수정]`으로 변경하였습니다. 

번거롭게 해서 죄송합니다.. 수정 부탁드립니다.. ㅜㅡㅜ

2024-07-22 20:10 UTC, daindaind commented
설정버튼은 정말 죄송합니다.. 필요하다면 임의로 하나 등록해서 일단 사용하실래요? 그냥 `<button>설정</button>` 이렇게 써도 좋습니다. 어차피 나중에야 변경하면 되니까요.. 빨리 디자이너님을 재촉하겠습니다ㅜㅡㅜ

2024-07-23 02:47 UTC, dydals3440 approved these changes

2024-07-23 02:47 UTC, dydals3440 commented on src/components/common/tooltip/Tooltip.style.js
> +    background-color: #ff0000;
background Color 상수화 시켜서 정의해서 사용해주세요!
아래도 동일합니다.

2024-07-23 02:47 UTC, dydals3440 commented on src/components/common/tooltip/Tooltip.style.js
> +    font-size: 9px;
font-size 상수화 시켜서 정의해서 사용해주세요!

2024-07-23 02:47 UTC, dydals3440 commented on src/components/common/tooltip/Tooltip.style.js
> +  text-align: center;
lint 제대로 동작안하고 있는 것 같은데 체크해서 code style formatting 해놓은거 지켜주세요!

2024-07-23 02:47 UTC, dydals3440 commented on src/pages/setting/FamilySettings/FamilySettings.jsx
> +  const [familyMembers, setFamilyMembers] = useState([
이렇게 useState안에 길게 넣어서, 테스트하지말고, 목데이터로 관리해주세요, 어짜피 실제 데이터 받으면 useState 내부는 useState([]) 이게 됩니다!

2024-07-23 02:47 UTC, dydals3440 commented on src/pages/setting/FamilySettings/FamilySettings.jsx
> +  const [isEditing, setIsEditing] = useState(null);
null보다는 false가 더 맞을 것 같습니다.

2024-07-23 02:47 UTC, dydals3440 commented on src/pages/setting/FamilySettings/FamilySettings.jsx
> +  const [selectedMember, setSelectedMember] = useState(null);
이부분도 false 동일.

2024-07-23 02:47 UTC, dydals3440 commented on src/pages/setting/FamilySettings/FamilySettings.style.js
> +  display: flex;
flex 부분도 상수화 시킨게 있는데, 사용할 수 있는 case면 사용해주세요.

2024-07-24 13:15 UTC, joyfulond commented on src/components/common/tooltip/Tooltip.style.js
> +    font-size: 9px;
제가 만든 공용 컴포넌트가 아닌데 수정한 부분이라 지웠습니다!

2024-08-04 17:32 UTC, merged