[Feat]feature/#41 내가 쓴 글 페이지 구현
Like-House/FE pull request #42
Opened 2024-07-19 13:02 UTC by joyfulond

## 🎈 어떤 이슈와 관련된 PR인가요?
> feature/#41

## 📝 해당 PR에서 작업한 내용을 설명해주세요.
> 이번 PR은 어떤 작업을 담고 있는지 간략히 설명해주세요!
- [x] myposts 페이지 구현

### 작업 내용과 관련된 스크린샷을 첨부해주세요. (선택 사항)
> 피그마 스크린샷
<img width="586" alt="스크린샷 2024-07-19 오후 9 58 36" src="https://github.com/user-attachments/assets/1d986858-e193-4d84-8f43-f740c77fec95">

> 작업 결과 스크린샷
<img width="1439" alt="스크린샷 2024-07-19 오후 9 59 55" src="https://github.com/user-attachments/assets/77a95822-a2a3-4e1c-b977-0b6cfc5c1c05">

## 💬 리뷰어 전달 사항
> 무한스크롤이 필요한가요? 필요한 것 같아서 만들었는데 필요없다면 수정하겠습니다.(ㅠㅠ) 20개 단위로 구현하였습니다!

2024-07-21 04:46 UTC, dydals3440 requested changes
반응형 확인한 이미지 리뷰에 첨부해서 올려주세요!

2024-07-22 20:19 UTC, daindaind approved these changes

2024-07-22 20:19 UTC, daindaind commented on src/pages/setting/MyPosts/MyPosts.style.js
> +
개인적으로 content들이 약간 낑겨서 힘들어보이는데, 이 부분은 모바일이나 태블릿 환경일 때 사진이 아래로 가도록 수정 가능할 것 같습니다! 

<img width="400" alt="image" src="https://github.com/user-attachments/assets/f95a5137-c1dd-4143-8ea7-5de52913afd3">



<img width="327" alt="image" src="https://github.com/user-attachments/assets/a052ea0f-8aed-4834-8821-675323684bff">

위와 같은 느낌이면 모바일에서도 충분히 잘 보일 것 같습니다.

2024-07-22 20:19 UTC, daindaind commented on src/pages/setting/MyPosts/MyPosts.jsx
> +  );
무한스크롤 구현해주셨는데 무한스크롤 맞을 겁니다!! 그리고 아마 추후에 tanstack query에서 제공하는 `useInfiniteQuery`인가 이 hook 써서 무한스크롤 구현할 것 같습니다. 참고로 이 hook은 실제 api를 연결해야 테스트하기에 수월할 겁니다. 그러니 해당 hook 사용법만 익혀놓으시면 될 것 같습니다! 이 코드는 지우지 말고 일단 나중에 수정하는 걸로 하면 될 것 같습니다.

아래 공식문서 참고해주세요!
https://tanstack.com/query/v4/docs/framework/react/reference/useInfiniteQuery

2024-07-23 02:54 UTC, dydals3440 approved these changes

2024-07-23 02:54 UTC, dydals3440 commented on src/pages/setting/MyPosts/MyPosts.style.js
> +
추가적으로 게시글 길어질떄, 어떻게 되는지 테스트해보세요, 게시글도 그렇고 댓글도 그렇고, 유저 이름이라던지 등등 텍스트 들어가는 요소 테스트할 떄, 길어지면 어떻게 되는지 테스트하고 이상있으시면

한줄로 줄이기
`.review {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  word-break: break-all;
}`

여러줄 줄이기
`.review {
  overflow: hidden;
  white-space: normal;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  word-break: keep-all;   // 문단으로 끊어져서 줄바꿈 됨
}
`
사용해서 수정해주세요!

2024-07-23 05:50 UTC, hijjoy approved these changes

2024-07-23 05:50 UTC, hijjoy commented on src/components/Settingbar/Settingbar.style.js
Container에 `z-index: 2;`속성을 넣음으로 인해 사이드바 보다 setting바가 위로 올라오게 되어 
사이드 바의 box-shadow가 뒤로 밀리게 됩니다.
위 사진이 피그마 아래가 구현 사진인데요 !
![스크린샷 2024-07-23 14 47 59](https://github.com/user-attachments/assets/3f8213e7-fe33-4fba-835c-2155adbab235)
![스크린샷 2024-07-23 14 48 04](https://github.com/user-attachments/assets/636eebd3-6f0f-4b28-a3ae-616c75a56309)
따라서 피그마처럼 구현하기 위해 sidebar에 z-index: 2; 보다 큰 수를 지정해주시거나 
다른 방법으로 해결해주시면 좋을 것 같습니다.

2024-07-24 14:35 UTC, joyfulond commented on src/pages/setting/MyPosts/MyPosts.style.js
> +
수정했습니다. 수정이 더 필요할 것 같긴 합니다...

2024-08-09 07:08 UTC, merged