[Feat]feature/#43 알림 설정 페이지 구현
Like-House/FE pull request #44
Opened 2024-07-19 13:47 UTC by joyfulond

## 🎈 어떤 이슈와 관련된 PR인가요?
> feature/#43

## 📝 해당 PR에서 작업한 내용을 설명해주세요.
> 이번 PR은 어떤 작업을 담고 있는지 간략히 설명해주세요!
- [x] 알림 설정 페이지 구현
- [x] 체크박스 오류 수정

### 작업 내용과 관련된 스크린샷을 첨부해주세요. (선택 사항)
> 피그마 스크린샷
<img width="657" alt="스크린샷 2024-07-19 오후 10 45 50" src="https://github.com/user-attachments/assets/12d8e36b-b2b5-41c6-b32b-6e502e37ca9b">

> 작업 결과 스크린샷
<img width="1440" alt="스크린샷 2024-07-19 오후 10 46 03" src="https://github.com/user-attachments/assets/1ea42a6f-186f-4997-8328-aacd8cf0a437">

## 💬 리뷰어 전달 사항
> 글씨 굵기나 체크박스 크기 정하는게 무지 어려운 것 같습니다...🥺 일단 체크박스 사이즈는 md로 했고 글씨도 임의로 조정했는데 보고 리뷰 달아주세요!!

2024-07-21 04:46 UTC, dydals3440 requested changes
반응형 확인한 이미지 리뷰에 첨부해서 올려주세요!

2024-07-22 20:28 UTC, daindaind approved these changes

2024-07-22 20:28 UTC, daindaind commented on src/pages/setting/NotificationSettings/NotificationSettings.style.js
> +
<img width="301" alt="image" src="https://github.com/user-attachments/assets/3daebbb4-94a1-4c8f-b709-65c976232ddb">


위 사진처럼 모바일 환경일 때 폰트 조금씩만 줄이고, 체크박스도 sm 사이즈로 주면 충분히 자연스럽게 모바일 UI 나올 것 같습니다. 이부분 한 번 고려해보시기 바랍니다!

2024-07-22 20:28 UTC, daindaind commented on src/components/common/checkbox/checkbox.jsx
> +    let checkBoxElement;
체크 박스가 클릭할 수 있는 요소인데 커서가 포인터로 변경되지 않아 사용자 입장에서 헷갈릴 수 있을 것 같습니다. 이 부분도 고려해주셔야 할 것 같습니다!

2024-07-23 02:57 UTC, dydals3440 approved these changes

2024-07-23 02:57 UTC, dydals3440 commented on src/components/common/checkbox/checkbox.jsx
> +      case 'outline':
case 'outline' 속성을 사용하지 않는 것 같은데 그럼 T굳이 switch / case 문을 사용하지 않고, 다른 방식으로 접근하는게 깔끔하지 않을까 싶습니다.

2024-08-09 07:11 UTC, merged