[Feat]feature/#45 로그아웃 페이지 구현
Like-House/FE pull request #46
Opened 2024-07-19 14:29 UTC by joyfulond

## 🎈 어떤 이슈와 관련된 PR인가요?
> feature/#45

## 📝 해당 PR에서 작업한 내용을 설명해주세요.
> 이번 PR은 어떤 작업을 담고 있는지 간략히 설명해주세요!
- [x] 로그아웃 페이지 구현

### 작업 내용과 관련된 스크린샷을 첨부해주세요. (선택 사항)
> 피그마 스크린샷
<img width="545" alt="스크린샷 2024-07-19 오후 11 27 35" src="https://github.com/user-attachments/assets/891d43cd-c6e5-498b-b74b-00253916d956">

> 작업 결과 스크린샷
<img width="1439" alt="스크린샷 2024-07-19 오후 11 28 06" src="https://github.com/user-attachments/assets/b6a857d2-1629-4b94-b529-2c6b0e121c04">
<img width="1440" alt="스크린샷 2024-07-19 오후 11 28 36" src="https://github.com/user-attachments/assets/18e19753-0d8b-4e63-863f-e87d33107513">

## 💬 리뷰어 전달 사항
> 확인을 누르면 확인만 있는 모달창이 뜨도록 구현하였습니다. 추후에 변동사항이 생기면 수정하겠습니다.

2024-07-21 04:47 UTC, dydals3440 requested changes
반응형 확인한 이미지 PR에 첨부해서 올려주세요!

2024-07-22 07:49 UTC, hijjoy approved these changes

2024-07-22 07:49 UTC, hijjoy commented on src/App.jsx
>            { path: 'family-space-settings', element: <FamilySpaceSettings /> },
모든_ 경로들 constants/path에 상수로 설정해 변경하는 것이 좋을 것 같습니다 ! 

PAGE_PATH 에 설정하거나
```
PAGE_PATH = {
    FAMILY_SPACE : "family-space-settings",
}
```
세팅 관련 페이지 따로 빼서 관리하는 등 
```
SETTING_PATH = {
	FAMILY_SPACE : "family-space-settings"
}
```

둘중 하나로 일단 상수화하면 좋을 것 같습니다 !

2024-07-22 20:44 UTC, daindaind approved these changes

2024-07-22 20:44 UTC, daindaind commented on src/pages/setting/Logout/Logout.jsx
> +  );
Alert 컴포넌트에서 아래와 같은 에러가 발생하고 있습니다.
```javascript
 console.js:288 Warning: React does not recognize the `singleButton` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `singlebutton` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
DOM 요소에 존재하지 않는 prop을 사용하려고 할 때 발생하는 오류로, 스타일 prop으로만 사용되는 거구나 라고 리액트가 이해할 수 있도록 스타일 컴포넌트에서 전달하려는 prop 앞에 $ 접두사를 붙여주어야 합니다.

```javascript
    <S.ModalBackground>
      <S.ModalContainer size={size}>
        <S.Icon>
          <img src={Exclamationmark} alt='exclamation mark' />
        </S.Icon>
        <S.ModalMessage>{message}</S.ModalMessage>
        {detailMessage && (
          <S.ModalDetailMessage>{detailMessage}</S.ModalDetailMessage>
        )}
        <S.ButtonContainer
          $singleButton={!onCancel}
          $singleButtonhasDetailMessage={!!detailMessage}
        >
          <S.Button onClick={onConfirm}>확인</S.Button>
          {onCancel && <S.Button onClick={onCancel}>취소</S.Button>}
        </S.ButtonContainer>
      </S.ModalContainer>
    </S.ModalBackground>
```

예를 들어 위와 같은 형태입니다. 


```javascript
const ButtonContainer = styled.div`
  ${ALIGN.ROW_CENTER};
  gap: ${({ $singleButton, $hasDetailMessage }) =>
    $singleButton ? '0' : $hasDetailMessage ? '100px' : '10px'};
`;
```

실제 스타일 파일에서는 해당 prop을 이렇게 전달 받아 사용할 수 있게 됩니다.
_styled-components $ 접두사_ 라고 검색하면 많이 나오니 한번 찾아보시는 것도 좋을 듯 합니다.
아래는 관련 문서입니다!
https://oliviakim.tistory.com/169

2024-07-22 20:44 UTC, daindaind commented on src/pages/setting/Logout/Logout.jsx
> +import Alert from '../../../components/common/alert/alert';
`console.js:288 Warning: Alert: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

Alert 컴포넌트에서 이런 경고도 나타나고 있는데, defaultProps이 더 이상 곧 리액트에서 지원하지 않을 것이라는 의미입니다. 
보통 prop에서 default value를 지정할 때는 아래와 같이 설정합니다.

```javascript
const Alert = ({ message, detailMessage = null, onConfirm, onCancel = null, isOpen }) 
```

아래는 defaultProps을 사용하면 안되는 이유가 담긴 문서입니다.
https://sophiabits.com/blog/stop-using-defaultprops

2024-07-22 20:44 UTC, daindaind commented on src/pages/setting/Logout/Logout.jsx
> +import Alert from '../../../components/common/alert/alert';
앞으로 개발하실 때 콘솔창도 같이 확인해주세요.
경고나 에러가 뜨면 실제 서비스할 때도, 개발을 진행할 때도 매우 불안정해집니다.

> 이런 경고 확인 부탁드립니다!
> 확인 후 해당 경고 및 오류 해결해주세요.

<img width="461" alt="image" src="https://github.com/user-attachments/assets/758951ca-ed73-4bb3-9f3f-7970d4983832">

2024-07-23 04:17 UTC, dydals3440 approved these changes

2024-07-23 04:17 UTC, dydals3440 commented on src/pages/setting/Logout/Logout.jsx
> +  );
좋은 리뷰입니다. 위에 말씀해주신 내용으로 수정 부탁드립니다~!

2024-07-31 10:20 UTC, hijjoy approved these changes

2024-07-31 10:20 UTC, hijjoy commented on src/pages/setting/Logout/Logout.jsx
> +export default function Logout() {
로그아웃 버튼을 눌렀다가 취소를 누르면 그 다음에 다시 로그아웃 버튼이 눌리지 않습니다 이부분 해결해주세요 ! 
(사용자가 잘못 취소를 눌렀다가 다시 로그아웃을 위해 로그아웃을 버튼을 눌렀을때 모달창이 떠야하는데 모달창이 뜨지 않습니다)

2024-08-09 06:56 UTC, merged