[Feat]feature/#47 탈퇴하기 페이지 구현
Like-House/FE pull request #48
Opened 2024-07-19 14:49 UTC by joyfulond

## 🎈 어떤 이슈와 관련된 PR인가요?
> feature/#47

## 📝 해당 PR에서 작업한 내용을 설명해주세요.
> 이번 PR은 어떤 작업을 담고 있는지 간략히 설명해주세요!
- [x] 탈퇴하기 페이지 구현
- [x] 공용 alert 줄바꿈 기능 추가

### 작업 내용과 관련된 스크린샷을 첨부해주세요. (선택 사항)
> 피그마 스크린샷
<img width="542" alt="스크린샷 2024-07-19 오후 11 49 22" src="https://github.com/user-attachments/assets/bd4a1af5-2dd1-4c35-98a8-a3db5ae0481e">

> 작업 결과 스크린샷
<img width="1440" alt="스크린샷 2024-07-19 오후 11 48 52" src="https://github.com/user-attachments/assets/a9f57bbc-ad88-4f1c-9b8e-a7222b01963f">
<img width="1440" alt="스크린샷 2024-07-19 오후 11 49 06" src="https://github.com/user-attachments/assets/c25323da-0038-46d8-8e13-c3950e5fc413">

## 💬 리뷰어 전달 사항
> 탈퇴하기 모달에 있는 detailMessage에 줄바꿈이 필요한 것 같아 alert에 줄바꿈 기능을 넣어주었습니다.

> 줄바꿈 사용방법입니다. 참고해주세요.
```
<Alert
        isOpen={isOpen}
        message='정말 탈퇴하시겠습니까?'
        detailMessage={
          '이 계정을 탈퇴하면 기존에 생성된 가족 공간은 자동으로 삭제되며\n초대된 가족들은 자동적으로 해당 가족 공간에서 탈퇴처리 됩니다.\n한 번 삭제된 가족 공간은 복구가 불가능합니다.'
        }
        onConfirm={handleConfirm}
        onCancel={handleClose}
      />
```

2024-07-21 04:47 UTC, dydals3440 requested changes
반응형 확인한 이미지 PR에 첨부해서 올려주세요!

2024-07-22 20:50 UTC, daindaind approved these changes

2024-07-22 20:50 UTC, daindaind commented on src/components/common/alert/alert.jsx
>  };
로그아웃 pr에 적어드렸던 $ 접두사 관련 이슈 해결하면, 같이 해결될 것 같으니 한 브랜치에서만 해결해주시면 될 것 같습니다!

2024-07-23 04:19 UTC, dydals3440 approved these changes

2024-07-23 04:19 UTC, dydals3440 commented on src/components/common/alert/alert.jsx
>  };
어떤 부분을 의도하고, 줄바꿈을 구현하신지는 모르겠지만
https://webclub.tistory.com/262
위의 단순 css를 활용해서, 줄 바꿈을 다양하게 하는 방법이 있으므로, 참고 부탁드립니다.
텍스트가 많아질 떄, 반응형 환경에서, 테스트 한번 부탁드리고 수정 부탁드립니다.

2024-07-31 10:24 UTC, hijjoy approved these changes

2024-07-31 10:24 UTC, hijjoy commented on src/pages/setting/DeleteAccount/DeleteAccount.jsx
> +export default function Logout() {
탈퇴하긴데 함수이름을 로그아웃으로 하신 이유가 있을까요 ?

2024-07-31 10:24 UTC, hijjoy commented on src/pages/setting/DeleteAccount/DeleteAccount.jsx
> +        isOpen={isOpen}
로그아웃과 마찬가지로 탈퇴하기 버튼을 누르고 취소를 누를경우
탈퇴하기 눌렀을때  다시 모달창이 뜨지 않습니다. 이부분 해결해서 올려주세요

2024-08-09 07:12 UTC, merged