[Feat] Feature/#32 AuthLayout navbar 구현
Like-House/FE pull request #52
Opened 2024-07-20 14:30 UTC by hijjoy

## 🎈 어떤 이슈와 관련된 PR인가요?
> feature/#32 

## 📝 해당 PR에서 작업한 내용을 설명해주세요.
> 이번 PR은 어떤 작업을 담고 있는지 간략히 설명해주세요!
- [x] navbar 구현 

### 작업 내용과 관련된 스크린샷을 첨부해주세요. (선택 사항)
> 피그마 스크린샷
![스크린샷 2024-07-20 23 25 04](https://github.com/user-attachments/assets/56bd4d85-43f0-46ea-b95b-b45905d71b7a)
![스크린샷 2024-07-20 23 25 10](https://github.com/user-attachments/assets/56c8721f-8b05-4930-9cd1-421497b9b004)

> 작업 결과 스크린샷
<img width="400" alt="스크린샷 2024-07-20 23 21 57" src="https://github.com/user-attachments/assets/d84f3750-e413-47d6-892f-28dbeacf493a">
<br/>
<img width="400" alt="스크린샷 2024-07-20 23 17 26" src="https://github.com/user-attachments/assets/2150de8d-6eb2-4e5a-9327-b55f8aecaf3b">

## 💬 리뷰어 전달 사항
> 리뷰어가 특별히 알아야 하는 사항을 설명해주세요.
1. Q/A 클릭시 이동경로와 프로필을 눌렀을때 이동경로가 정확하지 않아 정확한 경로로 구현하지 않았습니다. 
2. 로그인 api 연결 이후 로그인 여부 판단을 어떤 방식으로 할지 정확히 결정하고 if (login) 과 data부분은 수정할 예정입니다.

2024-07-21 04:49 UTC, dydals3440 requested changes
반응형 확인한 이미지 PR에 첨부해서 올려주세요!

2024-07-22 21:10 UTC, daindaind approved these changes

2024-07-22 21:10 UTC, daindaind commented on src/components/common/navbar/Navbar.jsx
> +				<NavLink to={`${PAGE_PATH.BASE}`}>서비스 이용</NavLink>
서비스 이용은 아마 경로가 `/`가 아닐 겁니다.. 로고를 누르면 `/`으로` 가고, 서비스 이용 페이지는 따로 있어야 할 것 같습니다. 

`SERVICE: 'service'` 이 경로가 서비스 이용을 누르면 이동하는 페이지입니다!

참고로 `/` 는 추후에 랜딩페이지가 올 것 같습니다. 해당 디자인은 디자이너님께 요청드리겠습니다.

2024-07-23 04:23 UTC, dydals3440 approved these changes

2024-07-23 04:23 UTC, dydals3440 commented on index.html
> +    <div id="modal"></div>
좋은 포탈 사용입니다. 🍠

2024-07-23 04:31 UTC, hijjoy commented on src/components/common/navbar/Navbar.jsx
> +				<NavLink to={`${PAGE_PATH.BASE}`}>서비스 이용</NavLink>
넵 ! 서비스 경로로 수정해 두었습니다. Q/A 경로에 해당하는 페이지도 디자이너님께 요청 드린걸로 알고있는데, 한번 확인부탁드립니다 ! 
혹시 프로필 경로를 feature/#55 에 해당하는 페이지로 연결해놨는데 이 방향이 맞을까요 ??

2024-07-24 15:50 UTC, merged