[FEAT]feature/#50 게시글 page 구현
Like-House/FE pull request #53
Opened 2024-07-21 11:50 UTC by hyeyoon23

## 🎈 어떤 이슈와 관련된 PR인가요?
> feature/#50

## 📝 해당 PR에서 작업한 내용을 설명해주세요.
> 이번 PR은 어떤 작업을 담고 있는지 간략히 설명해주세요!
- [ ] 작업 1
- [ ] 작업 2
- [ ] 작업 3

### 작업 내용과 관련된 스크린샷을 첨부해주세요. (선택 사항)
> 피그마 스크린샷

> 작업 결과 스크린샷

## 💬 리뷰어 전달 사항
> 리뷰어가 특별히 알아야 하는 사항을 설명해주세요.
> ex. ~파일에서 ~기능을 구현했는데 이렇게 하는게 과연 맞는 방식일까요?

2024-07-22 21:22 UTC, daindaind approved these changes

2024-07-22 21:22 UTC, daindaind commented on src/pages/main/MainPage.style.js
> +
<img width="550" alt="image" src="https://github.com/user-attachments/assets/59b9c59c-f724-407a-b7b6-137d83181ae7">
<img width="550" alt="image" src="https://github.com/user-attachments/assets/d4136517-601e-4224-b051-decad22688f1">

두 화면을 비교해보면, content 길이에 따라 메뉴가 더 오른쪽에 있기도 하고, 왼쪽으로 붙기도 합니다. 
메뉴 버튼이 이렇게 왔다갔다 하는게 사용자 입장에서는 분명 좋은 경험은 아닐 겁니다.<br /><br />


> 이런 식으로 content 길이가 어떻게 되든, 메뉴 위치가 일관성있어야 한다고 생각합니다!

<img width="550" alt="image" src="https://github.com/user-attachments/assets/2f64b003-8f39-479e-bfa4-d577cc464255">

2024-07-23 04:54 UTC, dydals3440 requested changes

2024-07-23 04:54 UTC, dydals3440 commented on src/pages/main/MainPage.jsx
> +  const [likes, setLikes] = useState(
코멘츠, 좋아요, 게시글 작성 등등 관련 부분은 굳이 reduce로 관리하지 않아도 될 것 같아요~
tanstack-query 사용 전제로 설명하겠습니다.
1. useQuery, useInfiniteQuery를 사용해서 데이터를 불러옵니다.
2. 게시글 작성시 useMutation / setQuery를 활용해서, InvalidateQueries를 통해 쿼리키를 fresh한 상태로 변경해주거나, setQuery를 활용하여, 글이 추가된 것을 기존 상태를 유지해서 작업해줄 수 있습니다.

-> 종합해서 이부분 로직 변경이 필요해보입니다. 자세한 글은 tanstack-query 공식문서 활용하면 좋을 것 같습니다.
https://tanstack.com/query/latest/docs/framework/react/overview

2024-07-23 04:54 UTC, dydals3440 commented on src/pages/main/MainPage.style.js
> +  display: flex;
flex 관련해서, theme 파일에 상수화 시켜놓은 부분이 있습니다. 해당 코드로 변경부탁드립니다.

2024-07-23 04:54 UTC, dydals3440 commented on src/pages/main/MainPage.style.js
> +  color: #888;
color 부분도, 상수화 시켜서, 없는 색상이면 추가해서 변경 부탁드립니다.

2024-07-23 04:54 UTC, dydals3440 commented on src/pages/main/MainPage.style.js
> +  font-size: 13px;
font-size 부분도 상수화 시킨 폰트 사이즈 사용해주시면 감사하겠습니다.

2024-07-23 04:54 UTC, dydals3440 commented on src/pages/main/MainPage.jsx
> +                {showCommentInput[post.id] && (
페이지에는 최소한 로직만 담고, 컴포넌트로, 각각 분리해서 관리하는게 좋아보입니다!

2024-08-10 14:05 UTC, closed without merging